### ISSUE TITLE
Use :classifier "aot" for cljs dependency in project.clj

### ISSUE THREAD

**Issue by ericnormand** [bhauman/figwheel-template#40]
Currently, the ClojureScript dependency in the outputted project.clj is

```clojure
[org.clojure/clojurescript "1.9.946"]
```

This fetches and uses the non-AOT compiled ClojureScript compiler. If you change it to 

```clojure
[org.clojure/clojurescript "1.9.946" :classifier "aot"]
```

you will get the AOT compiled version, which will cut the startup time of Figwheel considerably.

**Comment by bhauman** [comment]
The only reason I haven't done this is because aot'd dependencies subvert declared dependencies in subtle and strange ways and this can be maddening to figure out.

I'm pretty sure you will not be able to override the AOT compiled version of tools.reader included in CLJS.

It would be nice to have a faster startup time but AOT conflicts require a pretty sophisticated user to figure out. Trade offs.

**Comment by ericnormand** [comment]
Gotcha. Oh well, I figured there was a reason.
